export { default as AlipayOutline } from '@ant-design/icons/lib/outline/AlipayOutline'
export { default as GithubOutline } from '@ant-design/icons/lib/outline/GithubOutline'
export { default as WechatOutline } from '@ant-design/icons/lib/outline/WechatOutline'
export { default as DashboardOutline } from '@ant-design/icons/lib/outline/DashboardOutline'
export { default as BellOutline } from '@ant-design/icons/lib/outline/BellOutline'
export { default as UserOutline } from '@ant-design/icons/lib/outline/UserOutline'
export { default as SettingOutline } from '@ant-design/icons/lib/outline/SettingOutline'
export { default as LogoutOutline } from '@ant-design/icons/lib/outline/LogoutOutline'
export { default as Html5Outline } from '@ant-design/icons/lib/outline/Html5Outline'
export { default as AreaChartOutline } from '@ant-design/icons/lib/outline/AreaChartOutline'
export { default as TeamOutline } from '@ant-design/icons/lib/outline/TeamOutline'
export { default as LockOutline } from '@ant-design/icons/lib/outline/LockOutline'
export { default as MailOutline } from '@ant-design/icons/lib/outline/MailOutline'
export { default as QuestionCircleOutline } from '@ant-design/icons/lib/outline/QuestionCircleOutline'
export { default as ExclamationCircleOutline } from '@ant-design/icons/lib/outline/ExclamationCircleOutline'


export { default as CheckCircleOutline } from '@ant-design/icons/lib/outline/CheckCircleOutline'
export { default as CloseCircleOutline } from '@ant-design/icons/lib/outline/CloseCircleOutline'